# Generated by Django 6.0.1 on 2026-03-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
